# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a8b1e27d9c56c4b6852d64fcff62b2612672a95f8fe5ac8e37ad159eb21257ddf0537572fe91bb7e6d1badb2f661b388541e29791b5bb164b35a35e65ad2c9c

test:
  secret_key_base: 2fb9bd92649b8716e2cb0e58164565db924a9700084d7569eb729b66f9eb0afbedee4fb0f575dc1615402a061964db544dd00a23f9b06a4fb3e57b38f0e25010

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
